---
spring:
  config:
    activate:
      on-profile: prd
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/디비_이름?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: MySQL 관리자 이름
    password: MySQL 비밀번호
  jpa:
    hibernate:
      ddl-auto: none
---
